name: 每日规则同步

on:
  schedule:
    # 每天凌晨2点运行
    - cron: '0 2 * * *'
  workflow_dispatch:
    # 允许手动触发

jobs:
  sync:
    name: 同步规则
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: 同步规则
        run: python rulehub.py sync
      
      - name: 配置Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: 检查是否有更改
        id: check_changes
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes detected"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: 提交更改
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git add rules/ index/
          git commit -m "自动同步: $(date +%Y-%m-%d)"
      
      - name: 创建Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 自动同步规则更新
          title: '[自动] 每日规则同步 $(date +%Y-%m-%d)'
          body: |
            此PR由GitHub Actions自动创建，包含最新的规则同步。
            
            **同步内容:**
            - 从配置的开源仓库拉取最新规则
            - 转换规则为标准格式
            - 更新规则索引
            
            请检查更改后合并。
          branch: auto-sync-${{ github.run_id }}
          base: main
          labels: automated,rules-sync